import { requireRole } from '@/app/_lib/auth-guard';
import ManageContestsClient from './_components/ManageContestsClient';

export const metadata = { title: 'Contest Management | Executive | NEUPC' };

const TEMP_CONTESTS = [
  {
    id: '1',
    slug: 'neupc-monthly-march-2026',
    title: 'NEUPC Monthly Contest — March 2026',
    description: 'Monthly internal contest for NEUPC members. Problems range from beginner to advanced.',
    platform: 'Vjudge',
    contest_url: 'https://vjudge.net/contest/neupc-march-2026',
    start_time: '2026-03-08T14:00:00',
    duration: 180,
    type: 'individual',
    division: 'open',
    status: 'upcoming',
    is_official: true,
    created_at: '2026-02-20T10:00:00',
    updated_at: '2026-02-25T08:00:00',
    participantCount: 34,
  },
  {
    id: '2',
    slug: 'iupc-qualifier-2026',
    title: 'IUPC Internal Qualifier 2026',
    description: 'Qualifier round to select the NEUPC team for the Inter-University Programming Contest.',
    platform: 'Codeforces',
    contest_url: 'https://codeforces.com/group/neupc/contest/qualifier2026',
    start_time: '2026-02-15T10:00:00',
    duration: 300,
    type: 'team',
    division: 'A',
    status: 'finished',
    is_official: true,
    created_at: '2026-01-15T09:00:00',
    updated_at: '2026-02-16T12:00:00',
    participantCount: 52,
  },
  {
    id: '3',
    slug: 'neupc-beginner-contest-feb',
    title: 'Beginner Friendly Contest — February',
    description: 'Introductory contest for freshmen and members new to competitive programming.',
    platform: 'Vjudge',
    contest_url: 'https://vjudge.net/contest/neupc-beginner-feb',
    start_time: '2026-02-05T15:00:00',
    duration: 120,
    type: 'individual',
    division: 'B',
    status: 'finished',
    is_official: false,
    created_at: '2026-01-28T11:00:00',
    updated_at: '2026-02-06T09:00:00',
    participantCount: 67,
  },
  {
    id: '4',
    slug: 'neupc-dp-special-contest',
    title: 'DP Special Round',
    description: 'A themed contest focused entirely on dynamic programming problems.',
    platform: 'Codeforces',
    contest_url: 'https://codeforces.com/group/neupc/contest/dp-special',
    start_time: '2026-03-20T16:00:00',
    duration: 150,
    type: 'individual',
    division: 'open',
    status: 'upcoming',
    is_official: false,
    created_at: '2026-02-28T10:00:00',
    updated_at: '2026-02-28T10:00:00',
    participantCount: 0,
  },
  {
    id: '5',
    slug: 'neupc-team-training-jan',
    title: 'Team Training Round — January',
    description: 'Internal team training session with ICPC-style problems.',
    platform: 'Vjudge',
    contest_url: 'https://vjudge.net/contest/neupc-team-jan',
    start_time: '2026-01-20T10:00:00',
    duration: 240,
    type: 'team',
    division: 'A',
    status: 'running',
    is_official: true,
    created_at: '2026-01-10T08:00:00',
    updated_at: '2026-01-20T10:30:00',
    participantCount: 18,
  },
];

export default async function ManageContestsPage() {
  const { user } = await requireRole(['executive', 'admin']);
  return <ManageContestsClient initialContests={TEMP_CONTESTS} userId={user.id} />;
}
