-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.account_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  sender_id uuid NOT NULL,
  is_admin boolean NOT NULL DEFAULT false,
  message text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT account_messages_pkey PRIMARY KEY (id),
  CONSTRAINT account_messages_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT account_messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.users(id)
);
CREATE TABLE public.achievements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  contest_name text NOT NULL,
  contest_url text,
  result text NOT NULL,
  year integer NOT NULL,
  category text,
  description text,
  achievement_date date,
  participants ARRAY,
  is_team boolean DEFAULT false,
  team_name text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  gallery_images jsonb DEFAULT '[]'::jsonb,
  featured_photo jsonb,
  platform text,
  profile_url text,
  is_featured boolean NOT NULL DEFAULT false,
  CONSTRAINT achievements_pkey PRIMARY KEY (id),
  CONSTRAINT achievements_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.activity_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  action text NOT NULL,
  entity_type text,
  entity_id uuid,
  details jsonb,
  ip_address text,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT activity_logs_pkey PRIMARY KEY (id),
  CONSTRAINT activity_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.admin_profiles (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  user_id uuid NOT NULL DEFAULT gen_random_uuid(),
  bio text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT admin_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT admin_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.advisor_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  user_id uuid NOT NULL DEFAULT gen_random_uuid(),
  position text,
  profile_link text,
  department text DEFAULT 'Computer Science & Engineering'::text,
  CONSTRAINT advisor_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT teacher_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.api_cache (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  cache_key text NOT NULL UNIQUE,
  cache_value jsonb NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT api_cache_pkey PRIMARY KEY (id)
);
CREATE TABLE public.badge_definitions (
  id smallint NOT NULL DEFAULT nextval('badge_definitions_id_seq'::regclass),
  code character varying NOT NULL UNIQUE,
  name character varying NOT NULL,
  description text,
  icon character varying,
  category character varying,
  criteria jsonb NOT NULL,
  points smallint DEFAULT 0,
  CONSTRAINT badge_definitions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.blog_comments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  blog_id uuid NOT NULL,
  user_id uuid NOT NULL,
  parent_id uuid,
  content text NOT NULL,
  is_approved boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT blog_comments_pkey PRIMARY KEY (id),
  CONSTRAINT blog_comments_blog_id_fkey FOREIGN KEY (blog_id) REFERENCES public.blog_posts(id),
  CONSTRAINT blog_comments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT blog_comments_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.blog_comments(id)
);
CREATE TABLE public.blog_posts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  title text NOT NULL,
  excerpt text,
  content text NOT NULL,
  thumbnail text,
  author_id uuid NOT NULL,
  category text CHECK (category = ANY (ARRAY['CP'::text, 'WebDev'::text, 'AI-ML'::text, 'Career'::text, 'News'::text, 'Tutorial'::text, 'Programming'::text, 'Other'::text])),
  tags ARRAY,
  read_time integer,
  views integer DEFAULT 0,
  likes integer DEFAULT 0,
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'published'::text, 'archived'::text])),
  published_at timestamp with time zone,
  is_featured boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT blog_posts_pkey PRIMARY KEY (id),
  CONSTRAINT blog_posts_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.users(id)
);
CREATE TABLE public.bootcamps (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text,
  thumbnail text,
  price numeric DEFAULT 0,
  status USER-DEFINED DEFAULT 'draft'::bootcamp_status,
  is_featured boolean DEFAULT false,
  batch_info text,
  start_date date,
  end_date date,
  max_students integer,
  total_duration integer DEFAULT 0,
  total_lessons integer DEFAULT 0,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  page_html text,
  subtitle text,
  category text,
  difficulty text,
  CONSTRAINT bootcamps_pkey PRIMARY KEY (id),
  CONSTRAINT bootcamps_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.budget_entries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text,
  amount numeric NOT NULL,
  entry_type text NOT NULL CHECK (entry_type = ANY (ARRAY['income'::text, 'expense'::text])),
  category text,
  event_id uuid,
  transaction_date date NOT NULL,
  receipt_url text,
  approved_by uuid,
  approved_at timestamp with time zone,
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT budget_entries_pkey PRIMARY KEY (id),
  CONSTRAINT budget_entries_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT budget_entries_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id),
  CONSTRAINT budget_entries_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.certificates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  certificate_number text NOT NULL UNIQUE,
  recipient_id uuid NOT NULL,
  event_id uuid,
  contest_id uuid,
  achievement_id uuid,
  title text NOT NULL,
  description text,
  certificate_type text DEFAULT 'participation'::text CHECK (certificate_type = ANY (ARRAY['participation'::text, 'completion'::text, 'achievement'::text, 'appreciation'::text])),
  certificate_url text,
  issue_date date NOT NULL,
  issued_by uuid,
  verified boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT certificates_pkey PRIMARY KEY (id),
  CONSTRAINT certificates_recipient_id_fkey FOREIGN KEY (recipient_id) REFERENCES public.users(id),
  CONSTRAINT certificates_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT certificates_contest_id_fkey FOREIGN KEY (contest_id) REFERENCES public.contests(id),
  CONSTRAINT certificates_achievement_id_fkey FOREIGN KEY (achievement_id) REFERENCES public.achievements(id),
  CONSTRAINT certificates_issued_by_fkey FOREIGN KEY (issued_by) REFERENCES public.users(id)
);
CREATE TABLE public.chat_conversations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  type text NOT NULL DEFAULT 'direct'::text CHECK (type = ANY (ARRAY['direct'::text, 'support'::text])),
  status text NOT NULL DEFAULT 'open'::text CHECK (status = ANY (ARRAY['open'::text, 'closed'::text, 'archived'::text])),
  subject text,
  created_by uuid NOT NULL,
  assigned_to uuid,
  last_message_at timestamp with time zone,
  message_count integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT chat_conversations_pkey PRIMARY KEY (id),
  CONSTRAINT chat_conversations_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT chat_conversations_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.users(id)
);
CREATE TABLE public.chat_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  conversation_id uuid NOT NULL,
  sender_id uuid NOT NULL,
  content text NOT NULL,
  message_type text NOT NULL DEFAULT 'text'::text CHECK (message_type = ANY (ARRAY['text'::text, 'system'::text, 'image'::text, 'file'::text])),
  metadata jsonb,
  is_edited boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  edited_at timestamp with time zone,
  deleted_at timestamp with time zone,
  CONSTRAINT chat_messages_pkey PRIMARY KEY (id),
  CONSTRAINT chat_messages_conversation_fkey FOREIGN KEY (conversation_id) REFERENCES public.chat_conversations(id),
  CONSTRAINT chat_messages_sender_fkey FOREIGN KEY (sender_id) REFERENCES public.users(id)
);
CREATE TABLE public.chat_participants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  conversation_id uuid NOT NULL,
  user_id uuid NOT NULL,
  last_read_at timestamp with time zone,
  last_read_message_id uuid,
  is_muted boolean NOT NULL DEFAULT false,
  is_archived boolean NOT NULL DEFAULT false,
  joined_at timestamp with time zone DEFAULT now(),
  CONSTRAINT chat_participants_pkey PRIMARY KEY (id),
  CONSTRAINT chat_participants_conversation_fkey FOREIGN KEY (conversation_id) REFERENCES public.chat_conversations(id),
  CONSTRAINT chat_participants_user_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT chat_participants_last_read_message_fkey FOREIGN KEY (last_read_message_id) REFERENCES public.chat_messages(id)
);
CREATE TABLE public.committee_members (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  position_id uuid NOT NULL,
  term_start date NOT NULL,
  term_end date,
  is_current boolean DEFAULT true,
  bio text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT committee_members_pkey PRIMARY KEY (id),
  CONSTRAINT committee_members_position_id_fkey FOREIGN KEY (position_id) REFERENCES public.committee_positions(id),
  CONSTRAINT committee_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.committee_positions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  category text CHECK (category = ANY (ARRAY['executive'::text, 'mentor'::text, 'advisor'::text])),
  display_order integer DEFAULT 0,
  responsibilities text,
  created_at timestamp with time zone DEFAULT now(),
  rank integer DEFAULT 99,
  CONSTRAINT committee_positions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.contact_submissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  email text NOT NULL,
  subject text,
  message text NOT NULL,
  status text DEFAULT 'new'::text CHECK (status = ANY (ARRAY['new'::text, 'read'::text, 'replied'::text, 'archived'::text])),
  replied_by uuid,
  replied_at timestamp with time zone,
  ip_address text,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT contact_submissions_pkey PRIMARY KEY (id),
  CONSTRAINT contact_submissions_replied_by_fkey FOREIGN KEY (replied_by) REFERENCES public.users(id)
);
CREATE TABLE public.contest_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  platform_id smallint NOT NULL,
  external_contest_id character varying NOT NULL,
  contest_name character varying NOT NULL,
  contest_url character varying,
  contest_date timestamp with time zone NOT NULL,
  duration_minutes smallint,
  rank integer,
  total_participants integer,
  problems_solved smallint DEFAULT 0,
  problems_attempted smallint DEFAULT 0,
  score numeric,
  old_rating smallint,
  new_rating smallint,
  rating_change smallint,
  is_rated boolean DEFAULT true,
  is_virtual boolean DEFAULT false,
  division character varying,
  created_at timestamp with time zone DEFAULT now(),
  total_problems smallint,
  problems_data jsonb,
  penalty integer,
  platform_contest_id character varying DEFAULT NULL::character varying,
  max_score numeric DEFAULT NULL::numeric,
  contest_end_date timestamp with time zone,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT contest_history_pkey PRIMARY KEY (id),
  CONSTRAINT contest_history_platform_id_fkey FOREIGN KEY (platform_id) REFERENCES public.platforms(id),
  CONSTRAINT contest_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.contest_participants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  contest_id uuid NOT NULL,
  user_id uuid NOT NULL,
  rank integer,
  score numeric,
  problems_solved integer,
  performance_data jsonb,
  registered_at timestamp with time zone DEFAULT now(),
  CONSTRAINT contest_participants_pkey PRIMARY KEY (id),
  CONSTRAINT contest_participants_contest_id_fkey FOREIGN KEY (contest_id) REFERENCES public.contests(id),
  CONSTRAINT contest_participants_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.contests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  title text NOT NULL,
  description text,
  platform text,
  contest_url text,
  start_time timestamp with time zone NOT NULL,
  duration integer NOT NULL,
  type text DEFAULT 'individual'::text CHECK (type = ANY (ARRAY['individual'::text, 'team'::text])),
  division text,
  status text DEFAULT 'upcoming'::text CHECK (status = ANY (ARRAY['upcoming'::text, 'running'::text, 'finished'::text])),
  is_official boolean DEFAULT false,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT contests_pkey PRIMARY KEY (id),
  CONSTRAINT contests_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.courses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  bootcamp_id uuid NOT NULL,
  title text NOT NULL,
  description text,
  order_index integer DEFAULT 0,
  is_published boolean DEFAULT true,
  total_duration integer DEFAULT 0,
  total_lessons integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT courses_pkey PRIMARY KEY (id),
  CONSTRAINT courses_bootcamp_id_fkey FOREIGN KEY (bootcamp_id) REFERENCES public.bootcamps(id)
);
CREATE TABLE public.difficulty_tiers (
  id smallint NOT NULL DEFAULT nextval('difficulty_tiers_id_seq'::regclass),
  code character varying NOT NULL UNIQUE,
  name character varying NOT NULL,
  min_rating smallint,
  max_rating smallint,
  color_hex character,
  display_order smallint DEFAULT 0,
  CONSTRAINT difficulty_tiers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.discussion_activity (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  discussion_id uuid NOT NULL,
  user_id uuid,
  action text NOT NULL,
  old_value text,
  new_value text,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT discussion_activity_pkey PRIMARY KEY (id),
  CONSTRAINT discussion_activity_discussion_id_fkey FOREIGN KEY (discussion_id) REFERENCES public.discussion_threads(id),
  CONSTRAINT discussion_activity_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.discussion_attachments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  discussion_id uuid,
  reply_id uuid,
  file_url text NOT NULL,
  file_name text NOT NULL,
  file_type text,
  file_size integer,
  uploaded_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT discussion_attachments_pkey PRIMARY KEY (id),
  CONSTRAINT discussion_attachments_discussion_id_fkey FOREIGN KEY (discussion_id) REFERENCES public.discussion_threads(id),
  CONSTRAINT discussion_attachments_reply_id_fkey FOREIGN KEY (reply_id) REFERENCES public.discussion_replies(id),
  CONSTRAINT discussion_attachments_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.users(id)
);
CREATE TABLE public.discussion_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  description text,
  icon text,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT discussion_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.discussion_replies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  thread_id uuid NOT NULL,
  author_id uuid NOT NULL,
  content text NOT NULL,
  parent_id uuid,
  is_solution boolean DEFAULT false,
  upvotes integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_staff_reply boolean DEFAULT false,
  responder_role text,
  is_accepted boolean DEFAULT false,
  attachments jsonb DEFAULT '[]'::jsonb,
  CONSTRAINT discussion_replies_pkey PRIMARY KEY (id),
  CONSTRAINT discussion_replies_thread_id_fkey FOREIGN KEY (thread_id) REFERENCES public.discussion_threads(id),
  CONSTRAINT discussion_replies_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.users(id),
  CONSTRAINT discussion_replies_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.discussion_replies(id)
);
CREATE TABLE public.discussion_threads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  category_id uuid,
  title text NOT NULL,
  content text NOT NULL,
  author_id uuid NOT NULL,
  tags ARRAY,
  is_pinned boolean DEFAULT false,
  is_locked boolean DEFAULT false,
  is_solved boolean DEFAULT false,
  views integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  type text DEFAULT 'general_question'::text CHECK (type = ANY (ARRAY['course_problem'::text, 'assignment_issue'::text, 'bug_report'::text, 'ui_issue'::text, 'feature_request'::text, 'general_question'::text, 'announcement'::text])),
  status text DEFAULT 'new'::text CHECK (status = ANY (ARRAY['new'::text, 'open'::text, 'investigating'::text, 'in_progress'::text, 'resolved'::text, 'closed'::text, 'acknowledged'::text])),
  bootcamp_id uuid,
  course_id uuid,
  module_id uuid,
  lesson_id uuid,
  platform text DEFAULT 'website'::text CHECK (platform = ANY (ARRAY['website'::text, 'mobile_app'::text, 'desktop_app'::text])),
  priority text DEFAULT 'normal'::text CHECK (priority = ANY (ARRAY['low'::text, 'normal'::text, 'high'::text, 'urgent'::text])),
  assigned_to uuid,
  resolved_at timestamp with time zone,
  resolved_by uuid,
  expected_resolution_date timestamp with time zone,
  is_announcement boolean DEFAULT false,
  reply_count integer DEFAULT 0,
  last_reply_at timestamp with time zone,
  last_reply_by uuid,
  search_tsv tsvector DEFAULT to_tsvector('english'::regconfig, ((COALESCE(title, ''::text) || ' '::text) || COALESCE(content, ''::text))),
  CONSTRAINT discussion_threads_pkey PRIMARY KEY (id),
  CONSTRAINT discussion_threads_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.discussion_categories(id),
  CONSTRAINT discussion_threads_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.users(id),
  CONSTRAINT discussion_threads_bootcamp_id_fkey FOREIGN KEY (bootcamp_id) REFERENCES public.bootcamps(id),
  CONSTRAINT discussion_threads_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id),
  CONSTRAINT discussion_threads_module_id_fkey FOREIGN KEY (module_id) REFERENCES public.modules(id),
  CONSTRAINT discussion_threads_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.lessons(id),
  CONSTRAINT discussion_threads_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.users(id),
  CONSTRAINT discussion_threads_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES public.users(id),
  CONSTRAINT discussion_threads_last_reply_by_fkey FOREIGN KEY (last_reply_by) REFERENCES public.users(id)
);
CREATE TABLE public.discussion_votes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  thread_id uuid,
  reply_id uuid,
  vote_type text NOT NULL CHECK (vote_type = ANY (ARRAY['up'::text, 'down'::text])),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT discussion_votes_pkey PRIMARY KEY (id),
  CONSTRAINT discussion_votes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT discussion_votes_thread_id_fkey FOREIGN KEY (thread_id) REFERENCES public.discussion_threads(id),
  CONSTRAINT discussion_votes_reply_id_fkey FOREIGN KEY (reply_id) REFERENCES public.discussion_replies(id)
);
CREATE TABLE public.enrollments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  bootcamp_id uuid NOT NULL,
  status USER-DEFINED DEFAULT 'active'::enrollment_status,
  enrolled_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  expires_at timestamp with time zone,
  payment_id text,
  payment_amount numeric,
  progress_percent integer DEFAULT 0,
  last_accessed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT enrollments_pkey PRIMARY KEY (id),
  CONSTRAINT enrollments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT enrollments_bootcamp_id_fkey FOREIGN KEY (bootcamp_id) REFERENCES public.bootcamps(id)
);
CREATE TABLE public.event_gallery (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  event_id uuid NOT NULL,
  url text NOT NULL,
  type text DEFAULT 'image'::text CHECK (type = ANY (ARRAY['image'::text, 'video'::text])),
  caption text,
  display_order integer DEFAULT 0,
  uploaded_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT event_gallery_pkey PRIMARY KEY (id),
  CONSTRAINT event_gallery_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT event_gallery_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.users(id)
);
CREATE TABLE public.event_organizers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  event_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role text,
  added_at timestamp with time zone DEFAULT now(),
  CONSTRAINT event_organizers_pkey PRIMARY KEY (id),
  CONSTRAINT event_organizers_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT event_organizers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.event_registration_members (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  registration_id uuid NOT NULL,
  user_id uuid NOT NULL,
  is_leader boolean NOT NULL DEFAULT false,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'accepted'::text, 'declined'::text])),
  responded_at timestamp with time zone,
  CONSTRAINT event_registration_members_pkey PRIMARY KEY (id),
  CONSTRAINT event_registration_members_reg_fkey FOREIGN KEY (registration_id) REFERENCES public.event_registrations(id),
  CONSTRAINT event_registration_members_user_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.event_registrations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  event_id uuid NOT NULL,
  user_id uuid NOT NULL,
  team_name text,
  team_members ARRAY,
  registration_data jsonb,
  status text DEFAULT 'registered'::text CHECK (status = ANY (ARRAY['registered'::text, 'confirmed'::text, 'cancelled'::text, 'attended'::text])),
  attended boolean DEFAULT false,
  certificate_issued boolean DEFAULT false,
  registered_at timestamp with time zone DEFAULT now(),
  CONSTRAINT event_registrations_pkey PRIMARY KEY (id),
  CONSTRAINT event_registrations_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT event_registrations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  title text NOT NULL,
  description text,
  content text,
  start_date timestamp with time zone NOT NULL,
  end_date timestamp with time zone,
  location text NOT NULL,
  venue_type text DEFAULT 'offline'::text CHECK (venue_type = ANY (ARRAY['online'::text, 'offline'::text, 'hybrid'::text])),
  cover_image text,
  category text,
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'upcoming'::text, 'ongoing'::text, 'completed'::text, 'cancelled'::text])),
  max_participants integer,
  registration_required boolean DEFAULT false,
  registration_deadline timestamp with time zone,
  is_featured boolean DEFAULT false,
  tags ARRAY,
  created_by uuid NOT NULL,
  approved_by uuid,
  approved_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  eligibility text DEFAULT 'all'::text,
  prerequisites text,
  participation_type text DEFAULT 'individual'::text CHECK (participation_type = ANY (ARRAY['individual'::text, 'team'::text])),
  team_size integer,
  CONSTRAINT events_pkey PRIMARY KEY (id),
  CONSTRAINT events_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT events_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id)
);
CREATE TABLE public.faq_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  description text,
  icon text,
  platforms ARRAY DEFAULT ARRAY['website'::text, 'mobile_app'::text, 'desktop_app'::text],
  display_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT faq_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.faq_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  category_id uuid NOT NULL,
  question text NOT NULL,
  answer text NOT NULL,
  is_popular boolean DEFAULT false,
  display_order integer DEFAULT 0,
  views integer DEFAULT 0,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT faq_items_pkey PRIMARY KEY (id),
  CONSTRAINT faq_items_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.faq_categories(id),
  CONSTRAINT faq_items_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.gallery_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  url text NOT NULL,
  type text DEFAULT 'image'::text CHECK (type = ANY (ARRAY['image'::text, 'video'::text])),
  caption text,
  event_id uuid,
  category text,
  tags ARRAY,
  display_order integer DEFAULT 0,
  is_featured boolean DEFAULT false,
  uploaded_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT gallery_items_pkey PRIMARY KEY (id),
  CONSTRAINT gallery_items_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT gallery_items_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.users(id)
);
CREATE TABLE public.join_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  full_name text NOT NULL,
  email text NOT NULL,
  student_id text NOT NULL,
  batch text NOT NULL,
  department text NOT NULL,
  phone text,
  interests text,
  codeforces_handle text,
  github text,
  reason text,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  rejection_reason text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT join_requests_pkey PRIMARY KEY (id),
  CONSTRAINT join_requests_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.users(id)
);
CREATE TABLE public.journey_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  year text NOT NULL,
  event text NOT NULL,
  icon text NOT NULL DEFAULT '🎯'::text,
  description text,
  display_order integer DEFAULT 0,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT journey_items_pkey PRIMARY KEY (id),
  CONSTRAINT journey_items_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.languages (
  id smallint NOT NULL DEFAULT nextval('languages_id_seq'::regclass),
  code character varying NOT NULL UNIQUE,
  name character varying NOT NULL,
  extension character varying,
  CONSTRAINT languages_pkey PRIMARY KEY (id)
);
CREATE TABLE public.leaderboard_cache (
  user_id uuid NOT NULL,
  global_rank integer,
  weekly_rank integer,
  monthly_rank integer,
  total_score numeric DEFAULT 0,
  weekly_score numeric DEFAULT 0,
  monthly_score numeric DEFAULT 0,
  total_solved integer DEFAULT 0,
  weekly_solved integer DEFAULT 0,
  monthly_solved integer DEFAULT 0,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT leaderboard_cache_pkey PRIMARY KEY (user_id),
  CONSTRAINT leaderboard_cache_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.learning_activity_daily (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  bootcamp_id uuid NOT NULL,
  activity_date date NOT NULL DEFAULT ((now() AT TIME ZONE 'utc'::text))::date,
  watch_time integer NOT NULL DEFAULT 0 CHECK (watch_time >= 0),
  completed_module_ids ARRAY NOT NULL DEFAULT '{}'::uuid[],
  completed_lesson_ids ARRAY NOT NULL DEFAULT '{}'::uuid[],
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT learning_activity_daily_pkey PRIMARY KEY (id),
  CONSTRAINT learning_activity_daily_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT learning_activity_daily_bootcamp_id_fkey FOREIGN KEY (bootcamp_id) REFERENCES public.bootcamps(id)
);
CREATE TABLE public.lessons (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  module_id uuid NOT NULL,
  title text NOT NULL,
  description text,
  content text,
  video_source USER-DEFINED DEFAULT 'none'::video_source_type,
  video_id text,
  video_url text,
  duration integer DEFAULT 0,
  order_index integer DEFAULT 0,
  is_free_preview boolean DEFAULT false,
  is_published boolean DEFAULT true,
  attachments jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lessons_pkey PRIMARY KEY (id),
  CONSTRAINT lessons_module_id_fkey FOREIGN KEY (module_id) REFERENCES public.modules(id)
);
CREATE TABLE public.member_achievements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  achievement_id uuid NOT NULL,
  user_id uuid NOT NULL,
  position text,
  CONSTRAINT member_achievements_pkey PRIMARY KEY (id),
  CONSTRAINT member_achievements_achievement_id_fkey FOREIGN KEY (achievement_id) REFERENCES public.achievements(id),
  CONSTRAINT member_achievements_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.member_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  student_id text NOT NULL UNIQUE,
  academic_session text NOT NULL,
  department text NOT NULL,
  semester text,
  cgpa numeric,
  interests ARRAY,
  linkedin text,
  github text,
  skills ARRAY,
  bio text,
  join_reason text,
  approved boolean,
  approved_by uuid,
  approved_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  facebook text,
  x_handle text,
  CONSTRAINT member_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT member_profiles_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id),
  CONSTRAINT member_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.member_progress (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  period text NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  problems_solved integer DEFAULT 0,
  contests_participated integer DEFAULT 0,
  rating_change integer,
  mentor_notes text,
  self_assessment text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT member_progress_pkey PRIMARY KEY (id),
  CONSTRAINT member_progress_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.member_statistics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  member_id uuid NOT NULL UNIQUE,
  codeforces_rating integer DEFAULT 0,
  codeforces_handle text,
  vjudge_handle text,
  atcoder_handle text,
  leetcode_handle text,
  total_solved integer DEFAULT 0,
  contests_participated integer DEFAULT 0,
  updated_at timestamp with time zone DEFAULT now(),
  last_sync_at timestamp with time zone DEFAULT now(),
  CONSTRAINT member_statistics_pkey PRIMARY KEY (id),
  CONSTRAINT member_statistics_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.member_profiles(id)
);
CREATE TABLE public.mentor_profiles (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  user_id uuid NOT NULL DEFAULT gen_random_uuid(),
  bio text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT mentor_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT mentor_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.mentorship_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  mentorship_id uuid NOT NULL,
  session_date timestamp with time zone NOT NULL,
  duration integer,
  topic text,
  notes text,
  attended boolean DEFAULT false,
  feedback text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT mentorship_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT mentorship_sessions_mentorship_id_fkey FOREIGN KEY (mentorship_id) REFERENCES public.mentorships(id),
  CONSTRAINT mentorship_sessions_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.mentorships (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  mentor_id uuid NOT NULL,
  mentee_id uuid NOT NULL,
  start_date date NOT NULL DEFAULT CURRENT_DATE,
  end_date date,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'completed'::text, 'paused'::text, 'cancelled'::text])),
  focus_area text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT mentorships_pkey PRIMARY KEY (id),
  CONSTRAINT mentorships_mentor_id_fkey FOREIGN KEY (mentor_id) REFERENCES public.users(id),
  CONSTRAINT mentorships_mentee_id_fkey FOREIGN KEY (mentee_id) REFERENCES public.users(id)
);
CREATE TABLE public.modules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  course_id uuid NOT NULL,
  title text NOT NULL,
  description text,
  order_index integer DEFAULT 0,
  is_published boolean DEFAULT true,
  total_duration integer DEFAULT 0,
  total_lessons integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT modules_pkey PRIMARY KEY (id),
  CONSTRAINT modules_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id)
);
CREATE TABLE public.notices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  content text NOT NULL,
  notice_type text DEFAULT 'general'::text CHECK (notice_type = ANY (ARRAY['general'::text, 'urgent'::text, 'event'::text, 'deadline'::text, 'achievement'::text])),
  priority text DEFAULT 'medium'::text CHECK (priority = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'critical'::text])),
  target_audience ARRAY,
  is_pinned boolean DEFAULT false,
  expires_at timestamp with time zone,
  attachments ARRAY,
  created_by uuid NOT NULL,
  views integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notices_pkey PRIMARY KEY (id),
  CONSTRAINT notices_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  title text NOT NULL,
  message text NOT NULL,
  notification_type text CHECK (notification_type = ANY (ARRAY['info'::text, 'success'::text, 'warning'::text, 'error'::text, 'event'::text, 'mention'::text, 'achievement'::text])),
  link text,
  is_read boolean DEFAULT false,
  read_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.participation_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  contest_name text NOT NULL,
  contest_url text,
  category text,
  year integer NOT NULL,
  participation_date date,
  result text,
  is_team boolean NOT NULL DEFAULT false,
  team_name text,
  team_members jsonb DEFAULT '[]'::jsonb,
  achievement_id uuid,
  notes text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  photos jsonb DEFAULT '[]'::jsonb,
  featured_photo jsonb,
  CONSTRAINT participation_records_pkey PRIMARY KEY (id),
  CONSTRAINT participation_records_achievement_id_fkey FOREIGN KEY (achievement_id) REFERENCES public.achievements(id),
  CONSTRAINT participation_records_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT participation_records_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.permissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  category text NOT NULL,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT permissions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.platforms (
  id smallint NOT NULL DEFAULT nextval('platforms_id_seq'::regclass),
  code character varying NOT NULL UNIQUE,
  name character varying NOT NULL,
  base_url character varying,
  problem_url_template character varying,
  profile_url_template character varying,
  has_rating boolean DEFAULT false,
  has_contests boolean DEFAULT false,
  is_active boolean DEFAULT true,
  display_order smallint DEFAULT 999,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT platforms_pkey PRIMARY KEY (id)
);
CREATE TABLE public.problem_analysis (
  problem_id uuid NOT NULL,
  summary text,
  key_concepts ARRAY,
  hints ARRAY,
  common_mistakes ARRAY,
  time_complexity character varying,
  space_complexity character varying,
  analyzed_at timestamp with time zone,
  model_version character varying,
  CONSTRAINT problem_analysis_pkey PRIMARY KEY (problem_id),
  CONSTRAINT problem_analysis_problem_id_fkey FOREIGN KEY (problem_id) REFERENCES public.problems(id)
);
CREATE TABLE public.problem_editorials (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  problem_id uuid NOT NULL UNIQUE,
  tutorial_url text,
  tutorial_content text,
  tutorial_solutions jsonb DEFAULT '[]'::jsonb,
  tutorial_extracted_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT problem_editorials_pkey PRIMARY KEY (id),
  CONSTRAINT problem_editorials_problem_id_fkey FOREIGN KEY (problem_id) REFERENCES public.problems(id)
);
CREATE TABLE public.problem_tags (
  problem_id uuid NOT NULL,
  tag_id smallint NOT NULL,
  source character varying DEFAULT 'platform'::character varying,
  confidence numeric,
  CONSTRAINT problem_tags_pkey PRIMARY KEY (problem_id, tag_id),
  CONSTRAINT problem_tags_problem_id_fkey FOREIGN KEY (problem_id) REFERENCES public.problems(id),
  CONSTRAINT problem_tags_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES public.tags(id)
);
CREATE TABLE public.problems (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  platform_id smallint NOT NULL,
  external_id character varying NOT NULL,
  contest_id character varying,
  name character varying NOT NULL,
  url character varying,
  difficulty_rating smallint,
  difficulty_tier_id smallint,
  time_limit_ms integer,
  memory_limit_kb integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  description text,
  input_format text,
  output_format text,
  constraints text,
  examples jsonb DEFAULT '[]'::jsonb,
  notes text,
  tutorial_url text,
  tutorial_content text,
  tutorial_extracted_at timestamp with time zone,
  tutorial_solutions jsonb DEFAULT '[]'::jsonb,
  CONSTRAINT problems_pkey PRIMARY KEY (id),
  CONSTRAINT problems_platform_id_fkey FOREIGN KEY (platform_id) REFERENCES public.platforms(id),
  CONSTRAINT problems_difficulty_tier_id_fkey FOREIGN KEY (difficulty_tier_id) REFERENCES public.difficulty_tiers(id)
);
CREATE TABLE public.rating_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  platform_id smallint NOT NULL,
  contest_id uuid,
  rating smallint NOT NULL,
  rating_change smallint,
  recorded_at timestamp with time zone NOT NULL,
  CONSTRAINT rating_history_pkey PRIMARY KEY (id),
  CONSTRAINT rating_history_platform_id_fkey FOREIGN KEY (platform_id) REFERENCES public.platforms(id),
  CONSTRAINT rating_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT rating_history_contest_id_fkey FOREIGN KEY (contest_id) REFERENCES public.contest_history(id)
);
CREATE TABLE public.resource_bookmarks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  resource_id uuid NOT NULL,
  user_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT resource_bookmarks_pkey PRIMARY KEY (id),
  CONSTRAINT resource_bookmarks_resource_id_fkey FOREIGN KEY (resource_id) REFERENCES public.resources(id),
  CONSTRAINT resource_bookmarks_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.resource_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  slug text NOT NULL UNIQUE,
  description text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT resource_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.resource_tag_map (
  resource_id uuid NOT NULL,
  tag_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT resource_tag_map_pkey PRIMARY KEY (resource_id, tag_id),
  CONSTRAINT resource_tag_map_resource_id_fkey FOREIGN KEY (resource_id) REFERENCES public.resources(id),
  CONSTRAINT resource_tag_map_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES public.resource_tags(id)
);
CREATE TABLE public.resource_tags (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  slug text NOT NULL UNIQUE,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT resource_tags_pkey PRIMARY KEY (id)
);
CREATE TABLE public.resource_views (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  resource_id uuid NOT NULL,
  user_id uuid,
  anon_id text,
  viewed_at timestamp with time zone NOT NULL DEFAULT now(),
  source text,
  CONSTRAINT resource_views_pkey PRIMARY KEY (id),
  CONSTRAINT resource_views_resource_id_fkey FOREIGN KEY (resource_id) REFERENCES public.resources(id),
  CONSTRAINT resource_views_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.resources (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text,
  url text NOT NULL,
  resource_type text DEFAULT 'article'::text CHECK (resource_type = ANY (ARRAY['image'::text, 'video'::text, 'rich_text'::text, 'youtube'::text, 'facebook_post'::text, 'linkedin_post'::text, 'x_post'::text, 'external_link'::text, 'file'::text])),
  category text NOT NULL,
  difficulty text CHECK (difficulty = ANY (ARRAY['beginner'::text, 'intermediate'::text, 'advanced'::text])),
  tags ARRAY,
  thumbnail text,
  is_free boolean DEFAULT true,
  is_featured boolean DEFAULT false,
  upvotes integer DEFAULT 0,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  content jsonb,
  embed_url text,
  file_url text,
  category_id uuid,
  visibility text NOT NULL DEFAULT 'members'::text CHECK (visibility = ANY (ARRAY['public'::text, 'members'::text])),
  status text NOT NULL DEFAULT 'published'::text CHECK (status = ANY (ARRAY['draft'::text, 'scheduled'::text, 'published'::text, 'archived'::text])),
  is_pinned boolean NOT NULL DEFAULT false,
  published_at timestamp with time zone,
  scheduled_for timestamp with time zone,
  search_tsv tsvector DEFAULT to_tsvector('simple'::regconfig, ((COALESCE(title, ''::text) || ' '::text) || COALESCE(description, ''::text))),
  CONSTRAINT resources_pkey PRIMARY KEY (id),
  CONSTRAINT resources_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT resources_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.resource_categories(id)
);
CREATE TABLE public.roadmaps (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  title text NOT NULL,
  description text,
  category text NOT NULL,
  difficulty text DEFAULT 'beginner'::text CHECK (difficulty = ANY (ARRAY['beginner'::text, 'intermediate'::text, 'advanced'::text])),
  thumbnail text,
  content jsonb,
  estimated_duration text,
  prerequisites ARRAY,
  created_by uuid,
  views integer DEFAULT 0,
  is_featured boolean DEFAULT false,
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'published'::text, 'archived'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT roadmaps_pkey PRIMARY KEY (id),
  CONSTRAINT roadmaps_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.role_permissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  role_id uuid NOT NULL,
  permission_id uuid NOT NULL,
  CONSTRAINT role_permissions_pkey PRIMARY KEY (id),
  CONSTRAINT role_permissions_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(id),
  CONSTRAINT role_permissions_permission_id_fkey FOREIGN KEY (permission_id) REFERENCES public.permissions(id)
);
CREATE TABLE public.roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE CHECK (name = ANY (ARRAY['guest'::text, 'member'::text, 'executive'::text, 'admin'::text, 'mentor'::text, 'advisor'::text])),
  description text,
  priority integer NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT roles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.solution_analysis (
  solution_id uuid NOT NULL,
  approach_name character varying,
  approach_explanation text,
  time_complexity character varying,
  space_complexity character varying,
  techniques_used ARRAY,
  optimization_tips ARRAY,
  learning_notes text,
  analyzed_at timestamp with time zone,
  model_version character varying,
  CONSTRAINT solution_analysis_pkey PRIMARY KEY (solution_id),
  CONSTRAINT solution_analysis_solution_id_fkey FOREIGN KEY (solution_id) REFERENCES public.solutions(id)
);
CREATE TABLE public.solutions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_solve_id uuid NOT NULL,
  submission_id uuid,
  source_code text NOT NULL,
  language_id smallint,
  verdict character varying,
  is_primary boolean DEFAULT false,
  personal_notes text,
  created_at timestamp with time zone DEFAULT now(),
  submitted_at timestamp with time zone,
  CONSTRAINT solutions_pkey PRIMARY KEY (id),
  CONSTRAINT solutions_language_id_fkey FOREIGN KEY (language_id) REFERENCES public.languages(id),
  CONSTRAINT solutions_user_solve_id_fkey FOREIGN KEY (user_solve_id) REFERENCES public.user_solves(id),
  CONSTRAINT solutions_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(id)
);
CREATE TABLE public.submissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  problem_id uuid,
  platform_id smallint NOT NULL,
  external_submission_id character varying NOT NULL,
  external_problem_id character varying,
  problem_name character varying,
  verdict character varying NOT NULL,
  language_id smallint,
  execution_time_ms integer,
  memory_kb integer,
  submitted_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT submissions_pkey PRIMARY KEY (id),
  CONSTRAINT submissions_language_id_fkey FOREIGN KEY (language_id) REFERENCES public.languages(id),
  CONSTRAINT submissions_platform_id_fkey FOREIGN KEY (platform_id) REFERENCES public.platforms(id),
  CONSTRAINT submissions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT submissions_problem_id_fkey FOREIGN KEY (problem_id) REFERENCES public.problems(id)
);
CREATE TABLE public.sync_checkpoints (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  platform character varying NOT NULL,
  sync_status character varying DEFAULT 'pending'::character varying,
  sync_started_at timestamp with time zone,
  sync_completed_at timestamp with time zone,
  last_checkpoint_at timestamp with time zone,
  last_synced_at timestamp with time zone,
  last_submission_id character varying,
  last_submission_date timestamp with time zone,
  last_contest_id character varying,
  last_rating_date timestamp with time zone,
  total_inserted integer DEFAULT 0,
  sync_count integer DEFAULT 0,
  error_message text,
  error_details jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sync_checkpoints_pkey PRIMARY KEY (id),
  CONSTRAINT sync_checkpoints_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.sync_jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  platform_id smallint NOT NULL,
  job_type character varying NOT NULL,
  status character varying NOT NULL DEFAULT 'pending'::character varying,
  priority smallint DEFAULT 0,
  scheduled_at timestamp with time zone DEFAULT now(),
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  total_items integer DEFAULT 0,
  processed_items integer DEFAULT 0,
  inserted_items integer DEFAULT 0,
  last_processed_id character varying,
  last_processed_at timestamp with time zone,
  retry_count smallint DEFAULT 0,
  error_message text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sync_jobs_pkey PRIMARY KEY (id),
  CONSTRAINT sync_jobs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT sync_jobs_platform_id_fkey FOREIGN KEY (platform_id) REFERENCES public.platforms(id)
);
CREATE TABLE public.tags (
  id smallint NOT NULL DEFAULT nextval('tags_id_seq'::regclass),
  code character varying NOT NULL UNIQUE,
  name character varying NOT NULL,
  category character varying,
  parent_id smallint,
  display_order smallint DEFAULT 0,
  CONSTRAINT tags_pkey PRIMARY KEY (id),
  CONSTRAINT tags_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.tags(id)
);
CREATE TABLE public.task_submissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  task_id uuid NOT NULL,
  user_id uuid NOT NULL,
  submission_url text,
  code text,
  notes text,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'completed'::text, 'late'::text, 'missed'::text])),
  reviewed_by uuid,
  feedback text,
  submitted_at timestamp with time zone DEFAULT now(),
  CONSTRAINT task_submissions_pkey PRIMARY KEY (id),
  CONSTRAINT task_submissions_task_id_fkey FOREIGN KEY (task_id) REFERENCES public.weekly_tasks(id),
  CONSTRAINT task_submissions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT task_submissions_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.users(id)
);
CREATE TABLE public.unsolved_attempts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  platform_id smallint NOT NULL,
  problem_id uuid,
  submission_id uuid NOT NULL UNIQUE,
  external_problem_id character varying,
  problem_name character varying,
  source_code text NOT NULL,
  language_id smallint,
  verdict character varying NOT NULL,
  execution_time_ms integer,
  memory_kb integer,
  submitted_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT unsolved_attempts_pkey PRIMARY KEY (id),
  CONSTRAINT unsolved_attempts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT unsolved_attempts_platform_id_fkey FOREIGN KEY (platform_id) REFERENCES public.platforms(id),
  CONSTRAINT unsolved_attempts_problem_id_fkey FOREIGN KEY (problem_id) REFERENCES public.problems(id),
  CONSTRAINT unsolved_attempts_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(id),
  CONSTRAINT unsolved_attempts_language_id_fkey FOREIGN KEY (language_id) REFERENCES public.languages(id)
);
CREATE TABLE public.user_badges (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  badge_id smallint NOT NULL,
  earned_at timestamp with time zone DEFAULT now(),
  metadata jsonb,
  CONSTRAINT user_badges_pkey PRIMARY KEY (id),
  CONSTRAINT user_badges_badge_id_fkey FOREIGN KEY (badge_id) REFERENCES public.badge_definitions(id),
  CONSTRAINT user_badges_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_daily_activity (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  activity_date date NOT NULL,
  problems_solved smallint DEFAULT 0,
  submissions_count smallint DEFAULT 0,
  solutions_added smallint DEFAULT 0,
  active_platforms ARRAY DEFAULT '{}'::smallint[],
  CONSTRAINT user_daily_activity_pkey PRIMARY KEY (id),
  CONSTRAINT user_daily_activity_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_goals (
  user_id uuid NOT NULL,
  daily_target smallint DEFAULT 3,
  weekly_target smallint DEFAULT 15,
  monthly_target smallint DEFAULT 50,
  notify_on_miss boolean DEFAULT true,
  notify_on_complete boolean DEFAULT true,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_goals_pkey PRIMARY KEY (user_id),
  CONSTRAINT user_goals_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_handles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  platform_id smallint NOT NULL,
  handle character varying NOT NULL,
  is_verified boolean DEFAULT false,
  verified_at timestamp with time zone,
  current_rating smallint,
  max_rating smallint,
  rank_title character varying,
  avatar_url character varying,
  last_synced_at timestamp with time zone,
  sync_enabled boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  clist_account_id integer,
  CONSTRAINT user_handles_pkey PRIMARY KEY (id),
  CONSTRAINT user_handles_platform_id_fkey FOREIGN KEY (platform_id) REFERENCES public.platforms(id),
  CONSTRAINT user_handles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_language_stats (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  language_id smallint NOT NULL,
  solved_count integer NOT NULL DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_language_stats_pkey PRIMARY KEY (id),
  CONSTRAINT user_language_stats_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT user_language_stats_language_id_fkey FOREIGN KEY (language_id) REFERENCES public.languages(id)
);
CREATE TABLE public.user_platform_stats (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  platform_id smallint NOT NULL,
  problems_solved integer DEFAULT 0,
  current_rating smallint,
  max_rating smallint,
  last_synced_at timestamp with time zone,
  updated_at timestamp with time zone DEFAULT now(),
  rank_title character varying,
  total_submissions integer DEFAULT 0,
  contest_count integer DEFAULT 0,
  CONSTRAINT user_platform_stats_pkey PRIMARY KEY (id),
  CONSTRAINT user_platform_stats_platform_id_fkey FOREIGN KEY (platform_id) REFERENCES public.platforms(id),
  CONSTRAINT user_platform_stats_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_progress (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  lesson_id uuid NOT NULL,
  bootcamp_id uuid NOT NULL,
  is_completed boolean DEFAULT false,
  completed_at timestamp with time zone,
  watch_time integer DEFAULT 0 CHECK (watch_time >= 0) NOT VALI),
  last_position integer DEFAULT 0,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_progress_pkey PRIMARY KEY (id),
  CONSTRAINT user_progress_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT user_progress_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.lessons(id),
  CONSTRAINT user_progress_bootcamp_id_fkey FOREIGN KEY (bootcamp_id) REFERENCES public.bootcamps(id)
);
CREATE TABLE public.user_roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  role_id uuid NOT NULL,
  assigned_by uuid,
  assigned_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone,
  CONSTRAINT user_roles_pkey PRIMARY KEY (id),
  CONSTRAINT user_roles_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(id),
  CONSTRAINT user_roles_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES public.users(id),
  CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_solves (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  problem_id uuid NOT NULL,
  first_solved_at timestamp with time zone NOT NULL,
  solve_count smallint DEFAULT 1,
  attempt_count smallint DEFAULT 1,
  best_time_ms integer,
  best_memory_kb integer,
  is_favorite boolean DEFAULT false,
  personal_rating smallint CHECK (personal_rating >= 1 AND personal_rating <= 5),
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_solves_pkey PRIMARY KEY (id),
  CONSTRAINT user_solves_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT user_solves_problem_id_fkey FOREIGN KEY (problem_id) REFERENCES public.problems(id)
);
CREATE TABLE public.user_stats (
  user_id uuid NOT NULL,
  total_solved integer DEFAULT 0,
  total_submissions integer DEFAULT 0,
  total_solutions integer DEFAULT 0,
  easy_solved integer DEFAULT 0,
  medium_solved integer DEFAULT 0,
  hard_solved integer DEFAULT 0,
  expert_solved integer DEFAULT 0,
  solved_800 integer DEFAULT 0,
  solved_900 integer DEFAULT 0,
  solved_1000 integer DEFAULT 0,
  solved_1100 integer DEFAULT 0,
  solved_1200 integer DEFAULT 0,
  solved_1300 integer DEFAULT 0,
  solved_1400 integer DEFAULT 0,
  solved_1500 integer DEFAULT 0,
  solved_1600 integer DEFAULT 0,
  solved_1700 integer DEFAULT 0,
  solved_1800 integer DEFAULT 0,
  solved_1900 integer DEFAULT 0,
  solved_2000_plus integer DEFAULT 0,
  current_streak integer DEFAULT 0,
  longest_streak integer DEFAULT 0,
  last_solve_date date,
  weighted_score numeric DEFAULT 0,
  updated_at timestamp with time zone DEFAULT now(),
  solved_this_week integer DEFAULT 0,
  solved_this_month integer DEFAULT 0,
  solved_2000 integer DEFAULT 0,
  solved_2100 integer DEFAULT 0,
  solved_2200 integer DEFAULT 0,
  solved_2300 integer DEFAULT 0,
  solved_2400 integer DEFAULT 0,
  solved_2500_plus integer DEFAULT 0,
  CONSTRAINT user_stats_pkey PRIMARY KEY (user_id),
  CONSTRAINT user_stats_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_tag_stats (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  tag_id smallint NOT NULL,
  problems_solved integer DEFAULT 0,
  problems_attempted integer DEFAULT 0,
  avg_difficulty numeric,
  mastery_level character varying DEFAULT 'beginner'::character varying,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_tag_stats_pkey PRIMARY KEY (id),
  CONSTRAINT user_tag_stats_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES public.tags(id),
  CONSTRAINT user_tag_stats_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_tier_stats (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  difficulty_tier_id smallint NOT NULL,
  solved_count integer NOT NULL DEFAULT 0,
  attempt_count integer NOT NULL DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_tier_stats_pkey PRIMARY KEY (id),
  CONSTRAINT user_tier_stats_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT user_tier_stats_tier_id_fkey FOREIGN KEY (difficulty_tier_id) REFERENCES public.difficulty_tiers(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL UNIQUE,
  full_name text NOT NULL,
  phone text,
  avatar_url text DEFAULT 'https://robohash.org/30d749d7-64e1-4f5f-a781-c2d5c238e0f5.png?set=set4'::text,
  email_verified boolean DEFAULT false,
  verification_token text,
  reset_token text,
  reset_token_expires timestamp with time zone DEFAULT now(),
  last_login timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  provider text DEFAULT 'google'::text,
  account_status text NOT NULL DEFAULT 'inActive'::text CHECK (account_status = ANY (ARRAY['active'::text, 'inActive'::text, 'rejected'::text, 'pending'::text, 'suspended'::text, 'banned'::text, 'locked'::text])),
  status_changed_at timestamp with time zone,
  status_changed_by uuid,
  suspension_expires_at timestamp with time zone,
  phone_verified boolean DEFAULT false,
  status_reason text,
  is_online boolean DEFAULT false,
  last_seen timestamp with time zone,
  extension_token text UNIQUE,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_status_changed_by_fkey FOREIGN KEY (status_changed_by) REFERENCES public.users(id)
);
CREATE TABLE public.website_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  value jsonb NOT NULL,
  category text,
  description text,
  updated_by uuid,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT website_settings_pkey PRIMARY KEY (id),
  CONSTRAINT website_settings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.weekly_tasks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text,
  difficulty text DEFAULT 'medium'::text CHECK (difficulty = ANY (ARRAY['easy'::text, 'medium'::text, 'hard'::text])),
  problem_links ARRAY,
  deadline timestamp with time zone NOT NULL,
  assigned_by uuid NOT NULL,
  target_audience text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT weekly_tasks_pkey PRIMARY KEY (id),
  CONSTRAINT weekly_tasks_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES public.users(id)
);